language: python
matrix:
    include:
        - "3.8"

services:
    - docker

install:
    - pip install pipenv
    - pipenv install

before_script:
    - docker-compose up -d --build
    
script:
    - docker-compose exec web python manage.py test