language: python
matrix:
    include:
        - "3.5"
        - "3.6"
        - "3.7"
        - "3.8"

services:
    - docker
    - postgresql

install:
    - pip install pipenv
    - pipenv install


before_script:
    - docker-compose up -d --build
    - python manage.py test