# Generated by Django 3.0.5 on 2020-04-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivedat', models.DateTimeField()),
                ('devicereportedtime', models.DateTimeField()),
                ('facility', models.SmallIntegerField(default=0)),
                ('priority', models.SmallIntegerField(default=0)),
                ('fromhost', models.CharField(max_length=60)),
                ('fromhostip', models.CharField(max_length=60)),
                ('message', models.TextField()),
                ('infounitid', models.PositiveIntegerField()),
                ('syslogtag', models.CharField(max_length=60)),
            ],
        ),
    ]
