# Generated by Django 3.0.5 on 2020-04-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.BigIntegerField(blank=True, null=True)),
                ('receivedat', models.DateTimeField()),
                ('devicereportedtime', models.DateTimeField()),
                ('facility', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('fromhost', models.CharField(max_length=60)),
                ('message', models.TextField()),
                ('ntseverity', models.IntegerField(blank=True, null=True)),
                ('importance', models.IntegerField(blank=True, null=True)),
                ('eventsource', models.CharField(blank=True, max_length=60, null=True)),
                ('eventuser', models.CharField(blank=True, max_length=60, null=True)),
                ('eventcategory', models.IntegerField(blank=True, null=True)),
                ('eventid', models.IntegerField(blank=True, null=True)),
                ('eventbinary', models.TextField(blank=True, null=True)),
                ('maxavailable', models.IntegerField(blank=True, null=True)),
                ('currusage', models.IntegerField(blank=True, null=True)),
                ('minusage', models.IntegerField(blank=True, null=True)),
                ('maxusage', models.IntegerField(blank=True, null=True)),
                ('infounitid', models.IntegerField()),
                ('syslogtag', models.CharField(max_length=60)),
                ('eventlogtype', models.CharField(blank=True, max_length=60, null=True)),
                ('genericfilename', models.CharField(blank=True, max_length=60, null=True)),
                ('systemid', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
